---
title: "graphs"
author: "Andrew Antaya"
date: "June 24, 2019"
output: html_notebook
---

```{r}
# Boggy Trail 2018 Counts
jpeg(filename = "figures/counts/BGT18_Counts_Small.jpeg",
     width=3.2,
     height=3.2,
     units="in",
     res=300)
## bottom, left, top, right
par(mar=c(2, 2, 1, 2))
barplot(BGT18counts$freq,
        col = c("#4472C4", "#ED7D31", "#FFC000"),
        main = "Boggy Creek Trail 2018",
        cex.main = 0.75,
        cex.lab = 0.5,
        cex.names = 0.75,
        axes = FALSE,
        xlab = NA,
        ylab = NA,
        ylim = c(0, 10000),
        las = 0)
axis(1, at = seq(0.7, 3.1, by=1.2), labels = c("Horses", "Cattle", "Elk"), cex.axis = 0.75)
mtext("Counts", 2, las = 0 , cex = 0.66, padj = -3)
text(0.7, 2775, "2775", pos = 3, cex = 0.75)
text(1.9, 114, "114", pos = 3, cex = 0.75)
text(3.1, 344, "344", pos = 3, cex = 0.75)
axis(2, at = seq(0, 10000, by=500), cex.axis = .5, padj = 2)
dev.off()
```

```{r}
# Boggy West 2017 Counts
jpeg(filename = "figures/counts/BGW17_Counts_Small.jpeg",
     width=3.2,
     height=3.2,
     units="in",
     res=300)
## bottom, left, top, right
par(mar=c(2, 2, 1, 2))
barplot(BGW17counts$freq,
        col = c("#4472C4", "#ED7D31", "#FFC000"),
        main = "Boggy Creek Timelapse 2017",
        cex.main = 0.75,
        cex.lab = 0.5,
        cex.names = 0.75,
        axes = FALSE,
        xlab = NA,
        ylab = NA,
        ylim = c(0, 10000),
        las = 0)
axis(1, at = seq(0.7, 3.1, by=1.2), labels = c("Horses", "Cattle", "Elk"), cex.axis = 0.75)
mtext("Counts", 2, las = 0 , cex = 0.66, padj = -3)
text(0.7, 7686, "7686", pos = 3, cex = 0.75)
text(1.9, 2095, "2095", pos = 3, cex = 0.75)
text(3.1, 1942, "1942", pos = 3, cex = 0.75)
axis(2, at = seq(0, 10000, by=500), cex.axis = .5, padj = 2)
dev.off()
```

```{r}
# Boggy West 2018 Counts
jpeg(filename = "figures/counts/BGW18_Counts_Small.jpeg",
     width=3.2,
     height=3.2,
     units="in",
     res=300)
## bottom, left, top, right
par(mar=c(2, 2, 1, 2))
barplot(BGW18counts$freq,
        col = c("#4472C4", "#ED7D31", "#FFC000"),
        main = "Boggy Creek Timelapse 2018",
        cex.main = 0.75,
        cex.lab = 0.5,
        cex.names = 0.75,
        axes = FALSE,
        xlab = NA,
        ylab = NA,
        ylim = c(0, 10000),
        las = 0)
axis(1, at = seq(0.7, 3.1, by=1.2), labels = c("Horses", "Cattle", "Elk"), cex.axis = 0.75)
mtext("Counts", 2, las = 0 , cex = 0.66, padj = -3)
text(0.7, 5135, "5135", pos = 3, cex = 0.75)
text(1.9, 199, "199", pos = 3, cex = 0.75)
text(3.1, 898, "898", pos = 3, cex = 0.75)
axis(2, at = seq(0, 10000, by=500), cex.axis = .5, padj = 2)
dev.off()
```

```{r}
# Boggy Exclosure 2018 Counts
jpeg(filename = "figures/counts/BGX18_Counts_Small.jpeg",
     width=3.2,
     height=3.2,
     units="in",
     res=300)
## bottom, left, top, right
par(mar=c(2, 2, 1, 2))
barplot(BGX18counts$freq,
        col = c("#4472C4", "#ED7D31", "#FFC000"),
        main = "Boggy Creek Exclosure 2018",
        cex.main = 0.75,
        cex.lab = 0.5,
        cex.names = 0.75,
        axes = FALSE,
        xlab = NA,
        ylab = NA,
        ylim = c(0, 10000),
        las = 0)
axis(1, at = seq(0.7, 3.1, by=1.2), labels = c("Horses", "Cattle", "Elk"), cex.axis = 0.75)
mtext("Counts", 2, las = 0 , cex = 0.66, padj = -3)
text(0.7, 0, "0", pos = 3, cex = 0.75)
text(1.9, 0, "0", pos = 3, cex = 0.75)
text(3.1, 634, "634", pos = 3, cex = 0.75)
axis(2, at = seq(0, 10000, by=500), cex.axis = .5, padj = 2)
dev.off()
```

```{r}
# Wildcat Timelapse 2017 Counts
jpeg(filename = "figures/counts/WCS17_Counts_Small.jpeg",
     width=3.2,
     height=3.2,
     units="in",
     res=300)
## bottom, left, top, right
par(mar=c(2, 2, 1, 2))
barplot(WCS17counts$freq,
        col = c("#4472C4", "#ED7D31", "#FFC000"),
        main = "Wildcat Creek Timelapse 2017",
        cex.main = 0.75,
        cex.lab = 0.5,
        cex.names = 0.75,
        axes = FALSE,
        xlab = NA,
        ylab = NA,
        ylim = c(0, 25000),
        las = 0)
axis(1, at = seq(0.7, 3.1, by=1.2), labels = c("Horses", "Cattle", "Elk"), cex.axis = 0.75)
mtext("Counts", 2, las = 0 , cex = 0.66, padj = -3)
text(0.7, 22906, "22906", pos = 3, cex = 0.75)
text(1.9, 13317, "13317", pos = 3, cex = 0.75)
text(3.1, 13486, "13486", pos = 3, cex = 0.75)
axis(2, at = seq(0, 25000, by=5000), cex.axis = .5, padj = 2)
dev.off()
```

```{r}
# Wildcat Timelapse 2018 Counts
jpeg(filename = "figures/counts/WCS18_Counts_Small.jpeg",
     width=3.2,
     height=3.2,
     units="in",
     res=300)
## bottom, left, top, right
par(mar=c(2, 2, 1, 2))
barplot(WCS18counts$freq,
        col = c("#4472C4", "#ED7D31", "#FFC000"),
        main = "Wildcat Creek Timelapse 2018",
        cex.main = 0.75,
        cex.lab = 0.5,
        cex.names = 0.75,
        axes = FALSE,
        xlab = NA,
        ylab = NA,
        ylim = c(0, 25000),
        las = 0)
axis(1, at = seq(0.7, 3.1, by=1.2), labels = c("Horses", "Cattle", "Elk"), cex.axis = 0.75)
mtext("Counts", 2, las = 0 , cex = 0.66, padj = -3)
text(0.7, 9400, "9400", pos = 3, cex = 0.75)
text(1.9, 6544, "6544", pos = 3, cex = 0.75)
text(3.1, 1817, "1817", pos = 3, cex = 0.75)
axis(2, at = seq(0, 25000, by=5000), cex.axis = .5, padj = 2)
dev.off()
```

```{r}
# Wildcat Trail 2018 Counts
jpeg(filename = "figures/counts/WCT18_Counts_Small.jpeg",
     width=3.2,
     height=3.2,
     units="in",
     res=300)
## bottom, left, top, right
par(mar=c(2, 2, 1, 2))
barplot(WCT18counts$freq,
        col = c("#4472C4", "#ED7D31", "#FFC000"),
        main = "Wildcat Creek Trail 2018",
        cex.main = 0.75,
        cex.lab = 0.5,
        cex.names = 0.75,
        axes = FALSE,
        xlab = NA,
        ylab = NA,
        ylim = c(0, 25000),
        las = 0)
axis(1, at = seq(0.7, 3.1, by=1.2), labels = c("Horses", "Cattle", "Elk"), cex.axis = 0.75)
mtext("Counts", 2, las = 0 , cex = 0.66, padj = -3)
text(0.7, 2071, "2071", pos = 3, cex = 0.75)
text(1.9, 342, "342", pos = 3, cex = 0.75)
text(3.1, 398, "398", pos = 3, cex = 0.75)
axis(2, at = seq(0, 25000, by=5000), cex.axis = .5, padj = 2)
dev.off()
```

```{r}
# Wildcat Exclosure 2018 Counts
jpeg(filename = "figures/counts/WCX18_Counts_Small.jpeg",
     width=3.2,
     height=3.2,
     units="in",
     res=300)
## bottom, left, top, right
par(mar=c(2, 2, 1, 2))
barplot(WCX18counts$freq,
        col = c("#4472C4", "#ED7D31", "#FFC000"),
        main = "Wildcat Creek Exclosure 2018",
        cex.main = 0.75,
        cex.lab = 0.5,
        cex.names = 0.75,
        axes = FALSE,
        xlab = NA,
        ylab = NA,
        ylim = c(0, 25000),
        las = 0)
axis(1, at = seq(0.7, 3.1, by=1.2), labels = c("Horses", "Cattle", "Elk"), cex.axis = 0.75)
mtext("Counts", 2, las = 0 , cex = 0.66, padj = -3)
text(0.7, 494, "494", pos = 3, cex = 0.75)
text(1.9, 0, "0", pos = 3, cex = 0.75)
text(3.1, 2110, "2110", pos = 3, cex = 0.75)
axis(2, at = seq(0, 25000, by=5000), cex.axis = .5, padj = 2)
dev.off()
```

### Plotting Groups

```{r}
# Boggy Trail 2018 Groups
jpeg(filename = "figures/BGT18_Groups_Small.jpeg",
     width=3.2,
     height=3.2,
     units="in",
     res=300)
## bottom, left, top, right
par(mar=c(2, 2, 2, 2))
barplot(BGT18grouptotals$groups,
        col = c("#4472C4", "#ED7D31", "#FFC000"),
        main = "Boggy Creek Trail 2018",
        cex.main = 0.75,
        cex.lab = 0.5,
        cex.names = 0.75,
        axes = FALSE,
        xlab = NA,
        ylab = NA,
        ylim = c(0, 250),
        las = 0)
axis(1, at = seq(0.7, 3.1, by=1.2), labels = c("Horses", "Cattle", "Elk"), cex.axis = 0.75)
mtext("Number of Groups", 2, las = 0 , cex = 0.66, padj = -3)
text(0.7, 129, "129", pos = 3, cex = 0.75)
text(1.9, 13, "13", pos = 3, cex = 0.75)
text(3.1, 36, "36", pos = 3, cex = 0.75)
axis(2, at = seq(0, 250, by=50), cex.axis = .5, padj = 2)
dev.off()
```

```{r}
# Boggy West 2017 Groups
jpeg(filename = "figures/BGW17_Groups_Small.jpeg",
     width=3.2,
     height=3.2,
     units="in",
     res=300)
par(mar=c(2, 2, 2, 2))
barplot(BGW17grouptotals$groups,
        col = c("#4472C4", "#ED7D31", "#FFC000"),
        main ="Boggy Creek Timelapse 2017",
        cex.main = 0.75,
        cex.lab = 0.5,
        cex.names = 0.75,
        axes = FALSE,
        xlab = NA,
        ylab = NA,
        ylim = c(0, 250),
        las = 0)
axis(1, at = seq(0.7, 3.1, by=1.2), labels = c("Horses", "Cattle", "Elk"), cex.axis = 0.75)
mtext("Number of Groups", 2, las = 0 , cex = 0.66, padj = -3)
text(0.7, 119, "119", pos = 3, cex = 0.75)
text(1.9, 43, "43", pos = 3, cex = 0.75)
text(3.1, 72, "72", pos = 3, cex = 0.75)
axis(2, at = seq(0, 250, by=50), cex.axis = .5, padj = 2)
dev.off()
```

```{r}
# Boggy West 2018 Groups
jpeg(filename = "figures/BGW18_Groups_Small.jpeg",
     width=3.2,
     height=3.2,
     units="in",
     res=300)
par(mar=c(2, 2, 2, 2))
barplot(BGW18grouptotals$groups,
        col = c("#4472C4", "#ED7D31", "#FFC000"),
        main ="Boggy Creek Timelapse 2018",
        cex.main = 0.75,
        cex.lab = 0.5,
        cex.names = 0.75,
        axes = FALSE,
        xlab = NA,
        ylab = NA,
        ylim = c(0, 250),
        las = 0)
axis(1, at = seq(0.7, 3.1, by=1.2), labels = c("Horses", "Cattle", "Elk"), cex.axis = 0.75)
mtext("Number of Groups", 2, las = 0 , cex = 0.66, padj = -3)
text(0.7, 74, "74", pos = 3, cex = 0.75)
text(1.9, 11, "11", pos = 3, cex = 0.75)
text(3.1, 57, "57", pos = 3, cex = 0.75)
axis(2, at = seq(0, 250, by=50), cex.axis = .5, padj = 2)
dev.off()
```

```{r}
# Boggy Exclosure 2018 Groups
jpeg(filename = "figures/BGX18_Groups_Small.jpeg",
     width=3.2,
     height=3.2,
     units="in",
     res=300)
par(mar=c(2, 2, 2, 2))
barplot(BGX18grouptotals$groups,
        col = c("#4472C4", "#ED7D31", "#FFC000"),
        main ="Boggy Creek Exclosure 2018",
        cex.main = 0.75,
        cex.lab = 0.5,
        cex.names = 0.75,
        axes = FALSE,
        xlab = NA,
        ylab = NA,
        ylim = c(0, 250),
        las = 0)
axis(1, at = seq(0.7, 3.1, by=1.2), labels = c("Horses", "Cattle", "Elk"), cex.axis = 0.75)
mtext("Number of Groups", 2, las = 0 , cex = 0.66, padj = -3)
text(0.7, 0, "0", pos = 3, cex = 0.75)
text(1.9, 0, "0", pos = 3, cex = 0.75)
text(3.1, 16, "16", pos = 3, cex = 0.75)
axis(2, at = seq(0, 250, by=50), cex.axis = .5, padj = 2)
dev.off()
```

```{r}
# Wildcat South 2017 Groups
jpeg(filename = "figures/WCS17_Groups_Small.jpeg",
     width=3.2,
     height=3.2,
     units="in",
     res=300)
par(mar=c(2, 2, 2, 2))
barplot(WCS17grouptotals$groups,
        col = c("#4472C4", "#ED7D31", "#FFC000"),
        main ="Wildcat Creek Timelapse 2017",
        cex.main = 0.75,
        cex.lab = 0.5,
        cex.names = 0.75,
        axes = FALSE,
        xlab = NA,
        ylab = NA,
        ylim = c(0, 250),
        las = 0)
axis(1, at = seq(0.7, 3.1, by=1.2), labels = c("Horses", "Cattle", "Elk"), cex.axis = 0.75)
mtext("Number of Groups", 2, las = 0 , cex = 0.66, padj = -3)
text(0.7, 218, "218", pos = 3, cex = 0.75)
text(1.9, 73, "73", pos = 3, cex = 0.75)
text(3.1, 135, "135", pos = 3, cex = 0.75)
axis(2, at = seq(0, 250, by=50), cex.axis = .5, padj = 2)
dev.off()
```

```{r}
# Wildcat South 2018 Groups
jpeg(filename = "figures/WCS18_Groups_Small.jpeg",
     width=3.2,
     height=3.2,
     units="in",
     res=300)
par(mar=c(2, 2, 2, 2))
barplot(WCS18grouptotals$groups,
        col = c("#4472C4", "#ED7D31", "#FFC000"),
        main ="Wildcat Creek Timelapse 2018",
        cex.main = 0.75,
        cex.lab = 0.5,
        cex.names = 0.75,
        axes = FALSE,
        xlab = NA,
        ylab = NA,
        ylim = c(0, 250),
        las = 0)
axis(1, at = seq(0.7, 3.1, by=1.2), labels = c("Horses", "Cattle", "Elk"), cex.axis = 0.75)
mtext("Number of Groups", 2, las = 0 , cex = 0.66, padj = -3)
text(0.7, 97, "97", pos = 3, cex = 0.75)
text(1.9, 23, "23", pos = 3, cex = 0.75)
text(3.1, 73, "73", pos = 3, cex = 0.75)
axis(2, at = seq(0, 250, by=50), cex.axis = .5, padj = 2)
dev.off()

```

```{r}
# Wildcat Trail 2018 Groups
jpeg(filename = "figures/WCT18_Groups_Small.jpeg",
     width=3.2,
     height=3.2,
     units="in",
     res=300)
par(mar=c(2, 2, 2, 2))
barplot(WCT18grouptotals$groups,
        col = c("#4472C4", "#ED7D31", "#FFC000"),
        main ="Wildcat Creek Trail 2018",
        cex.main = 0.75,
        cex.lab = 0.5,
        cex.names = 0.75,
        axes = FALSE,
        xlab = NA,
        ylab = NA,
        ylim = c(0, 250),
        las = 0)
axis(1, at = seq(0.7, 3.1, by=1.2), labels = c("Horses", "Cattle", "Elk"), cex.axis = 0.75)
mtext("Number of Groups", 2, las = 0 , cex = 0.66, padj = -3)
text(0.7, 91, "91", pos = 3, cex = 0.75)
text(1.9, 16, "16", pos = 3, cex = 0.75)
text(3.1, 52, "52", pos = 3, cex = 0.75)
axis(2, at = seq(0, 250, by=50), cex.axis = .5, padj = 2)
dev.off()
```

```{r}
# Wildcat Exclosure 2018 Groups
jpeg(filename = "figures/WCX18_Groups_Small.jpeg",
     width=3.2,
     height=3.2,
     units="in",
     res=300)
par(mar=c(2, 2, 2, 2))
barplot(WCX18grouptotals$groups,
        col = c("#4472C4", "#ED7D31", "#FFC000"),
        main ="Wildcat Creek Exclosure 2018",
        cex.main = 0.75,
        cex.lab = 0.5,
        cex.names = 0.75,
        axes = FALSE,
        xlab = NA,
        ylab = NA,
        ylim = c(0, 250),
        las = 0)
axis(1, at = seq(0.7, 3.1, by=1.2), labels = c("Horses", "Cattle", "Elk"), cex.axis = 0.75)
mtext("Number of Groups", 2, las = 0 , cex = 0.66, padj = -3)
text(0.7, 47, "47", pos = 3, cex = 0.75)
text(1.9, 0, "0", pos = 3, cex = 0.75)
text(3.1, 47, "47", pos = 3, cex = 0.75)
axis(2, at = seq(0, 250, by=50), cex.axis = .5, padj = 2)
dev.off()
```

```{r}
### Boggy Trail 2018 Site Use by Time of Day 
jpeg(filename = "figures/timeofday/BGT18_Time_Small.jpg",
     width=6.5,
     height=6.5,
     units="in",
     res=300)
## bottom, left, top, right
par(mar=c(5, 4, 2, 2))
matplot(c(0:23), BGT18time, 
        type = c("o"),
        main = "Boggy Creek Trail 2018",
        axes = FALSE,
        xlab = NA,
        ylab = NA,
        ylim = c(0,2000),
        pch = 16,
        lty = 1,
        lwd = 2,
        col = c("#4472C4", "#ED7D31", "#FFC000"))
legend("topleft", 
       legend = c("Horses", "Cattle", "Elk"),
       cex = 1.25,
       col = c("#4472C4", "#ED7D31", "#FFC000"), 
       pch = 16)
axis(2, at = seq(0, 2000, by=100), labels = c(seq(0, 2000, by=100)), cex.axis = 0.75)
axis(1, at = 0:23, labels = (hrs), las = 2, cex.axis = 0.75)
mtext("Time of Day (24hrs)", 1, las = 0 , cex = 1, padj = 6)
mtext("Count", 2, las = 0 , cex = 1, padj = -3)
dev.off()
```

```{r}
### Boggy West Timelapse 2017 Site Use by Time of Day 
jpeg(filename = "figures/timeofday/BGW17_Time_Small.jpg",
     width=6.5,
     height=6.5,
     units="in",
     res=300)
## bottom, left, top, right
par(mar=c(5, 4, 2, 2))
matplot(c(0:23), BGW17time, 
        type = c("o"),
        main = "Boggy Creek Timelapse 2017",
        axes = FALSE,
        xlab = NA,
        ylab = NA,
        ylim = c(0,2000),
        pch = 16,
        lty = 1,
        lwd = 2,
        col = c("#4472C4", "#ED7D31", "#FFC000"))
legend("topleft", 
       legend = c("Horses", "Cattle", "Elk"),
       cex = 1.25,
       col = c("#4472C4", "#ED7D31", "#FFC000"), 
       pch = 16)
axis(2, at = seq(0, 2000, by=100), labels = c(seq(0, 2000, by=100)), cex.axis = 0.75)
axis(1, at = 0:23, labels = (hrs), las = 2, cex.axis = 0.75)
mtext("Time of Day (24hrs)", 1, las = 0 , cex = 1, padj = 6)
mtext("Count", 2, las = 0 , cex = 1, padj = -3)
dev.off()
```

```{r}
### Boggy West Timelapse 2018 Site Use by Time of Day 
jpeg(filename = "figures/timeofday/BGW18_Time_Small.jpg",
     width=6.5,
     height=6.5,
     units="in",
     res=300)
## bottom, left, top, right
par(mar=c(5, 4, 2, 2))
matplot(c(0:23), BGW18time, 
        type = c("o"),
        main = "Boggy Creek Timelapse 2018",
        axes = FALSE,
        xlab = NA,
        ylab = NA,
        ylim = c(0,2000),
        pch = 16,
        lty = 1,
        lwd = 2,
        col = c("#4472C4", "#ED7D31", "#FFC000"))
legend("topleft", 
       legend = c("Horses", "Cattle", "Elk"),
       cex = 1.25,
       col = c("#4472C4", "#ED7D31", "#FFC000"), 
       pch = 16)
axis(2, at = seq(0, 2000, by=100), labels = c(seq(0, 2000, by=100)), cex.axis = 0.75)
axis(1, at = 0:23, labels = (hrs), las = 2, cex.axis = 0.75)
mtext("Time of Day (24hrs)", 1, las = 0 , cex = 1, padj = 6)
mtext("Count", 2, las = 0 , cex = 1, padj = -3)
dev.off()
```

```{r}
### Boggy Exclosure 2018 Site Use by Time of Day 
jpeg(filename = "figures/timeofday/BGX18_Time_Small.jpg",
     width=6.5,
     height=6.5,
     units="in",
     res=300)
## bottom, left, top, right
par(mar=c(5, 4, 2, 2))
matplot(c(0:23), BGX18time, 
        type = c("o"),
        main = "Boggy Creek Exclosure 2018",
        axes = FALSE,
        xlab = NA,
        ylab = NA,
        ylim = c(0,2000),
        pch = 16,
        lty = 1,
        lwd = 2,
        col = c("#4472C4", "#ED7D31", "#FFC000"))
legend("topleft", 
       legend = c("Horses", "Cattle", "Elk"),
       cex = 1.25,
       col = c("#4472C4", "#ED7D31", "#FFC000"), 
       pch = 16)
axis(2, at = seq(0, 2000, by=100), labels = c(seq(0, 2000, by=100)), cex.axis = 0.75)
axis(1, at = 0:23, labels = (hrs), las = 2, cex.axis = 0.75)
mtext("Time of Day (24hrs)", 1, las = 0 , cex = 1, padj = 6)
mtext("Count", 2, las = 0 , cex = 1, padj = -3)
dev.off()
```

```{r}
### Wildcat Timelapse 2017 Site Use by Time of Day 
jpeg(filename = "figures/timeofday/WCS17_Time_Small.jpg",
     width=6.5,
     height=6.5,
     units="in",
     res=300)
## bottom, left, top, right
par(mar=c(5, 4, 2, 2))
matplot(c(0:23), WCS17time, 
        type = c("o"),
        main = "Wildcat Creek Timelapse 2017",
        axes = FALSE,
        xlab = NA,
        ylab = NA,
        ylim = c(0,4500),
        pch = 16,
        lty = 1,
        lwd = 2,
        col = c("#4472C4", "#ED7D31", "#FFC000"))
legend("topleft", 
       legend = c("Horses", "Cattle", "Elk"),
       cex = 1.25,
       col = c("#4472C4", "#ED7D31", "#FFC000"), 
       pch = 16)
axis(2, at = seq(0, 4500, by=500), labels = c(seq(0, 4500, by=500)), cex.axis = 0.75)
axis(1, at = 0:23, labels = (hrs), las = 2, cex.axis = 0.75)
mtext("Time of Day (24hrs)", 1, las = 0 , cex = 1, padj = 6)
mtext("Count", 2, las = 0 , cex = 1, padj = -3)
dev.off()
```

```{r}
### Wildcat Timelapse 2018 Site Use by Time of Day 
jpeg(filename = "figures/timeofday/WCS18_Time_Small.jpg",
     width=6.5,
     height=6.5,
     units="in",
     res=300)
## bottom, left, top, right
par(mar=c(5, 4, 2, 2))
matplot(c(0:23), WCS18time, 
        type = c("o"),
        main = "Wildcat Creek Timelapse 2018",
        axes = FALSE,
        xlab = NA,
        ylab = NA,
        ylim = c(0,2000),
        pch = 16,
        lty = 1,
        lwd = 2,
        col = c("#4472C4", "#ED7D31", "#FFC000"))
legend("topleft", 
       legend = c("Horses", "Cattle", "Elk"),
       cex = 1.25,
       col = c("#4472C4", "#ED7D31", "#FFC000"), 
       pch = 16)
axis(2, at = seq(0, 2000, by=100), labels = c(seq(0, 2000, by=100)), cex.axis = 0.75)
axis(1, at = 0:23, labels = (hrs), las = 2, cex.axis = 0.75)
mtext("Time of Day (24hrs)", 1, las = 0 , cex = 1, padj = 6)
mtext("Count", 2, las = 0 , cex = 1, padj = -3)
dev.off()
```

```{r}
### Wildcat Trail 2018 Site Use by Time of Day 
jpeg(filename = "figures/timeofday/WCT18_Time_Small.jpg",
     width=6.5,
     height=6.5,
     units="in",
     res=300)
## bottom, left, top, right
par(mar=c(5, 4, 2, 2))
matplot(c(0:23), WCT18time, 
        type = c("o"),
        main = "Wildcat Creek Trail 2018",
        axes = FALSE,
        xlab = NA,
        ylab = NA,
        ylim = c(0,2000),
        pch = 16,
        lty = 1,
        lwd = 2,
        col = c("#4472C4", "#ED7D31", "#FFC000"))
legend("topleft", 
       legend = c("Horses", "Cattle", "Elk"),
       cex = 1.25,
       col = c("#4472C4", "#ED7D31", "#FFC000"), 
       pch = 16)
axis(2, at = seq(0, 2000, by=100), labels = c(seq(0, 2000, by=100)), cex.axis = 0.75)
axis(1, at = 0:23, labels = (hrs), las = 2, cex.axis = 0.75)
mtext("Time of Day (24hrs)", 1, las = 0 , cex = 1, padj = 6)
mtext("Count", 2, las = 0 , cex = 1, padj = -3)
dev.off()
```

```{r}
### Wildcat Exclosure 2018 Site Use by Time of Day 
jpeg(filename = "figures/timeofday/WCX18_Time_Small.jpg",
     width=6.5,
     height=6.5,
     units="in",
     res=300)
## bottom, left, top, right
par(mar=c(5, 4, 2, 2))
matplot(c(0:23), WCX18time, 
        type = c("o"),
        main = "Wildcat Creek Exclosure 2018",
        axes = FALSE,
        xlab = NA,
        ylab = NA,
        ylim = c(0,2000),
        pch = 16,
        lty = 1,
        lwd = 2,
        col = c("#4472C4", "#ED7D31", "#FFC000"))
legend("topleft", 
       legend = c("Horses", "Cattle", "Elk"),
       cex = 1.25,
       col = c("#4472C4", "#ED7D31", "#FFC000"), 
       pch = 16)
axis(2, at = seq(0, 2000, by=100), labels = c(seq(0, 2000, by=100)), cex.axis = 0.75)
axis(1, at = 0:23, labels = (hrs), las = 2, cex.axis = 0.75)
mtext("Time of Day (24hrs)", 1, las = 0 , cex = 1, padj = 6)
mtext("Count", 2, las = 0 , cex = 1, padj = -3)
dev.off()
```

```{r}
jpeg(filename = "figures/monsoon/BGW17_Monsoon_Small.jpg",
     width=6.5,
     height=6.5,
     units="in",
     res=300)
## bottom, left, top, right
par(mar=c(5, 4, 4, 2))
barplot(BGW17groups, 
        col = c("#4472C4", "#ED7D31", "#FFC000"),
        main = "Boggy Creek Timelapse 2017",
        sub = "Number of Groups by Monsoonal Period",
        ylim = c(0,150),
        axes = FALSE,
        border = "black",
        beside = TRUE,
        legend = rownames(BGW17groups),
        font.axis = 3,
        font.lab = 2)
axis(2, at = seq(0, 150, by=10), labels = c(seq(0, 150, by=10)), cex.axis = 0.75, las = 2)
text(1.5, 8, "8", pos = 3, cex = 0.75)
text(2.5, 2, "2", pos = 3, cex = 0.75)
text(3.5, 12, "12", pos = 3, cex = 0.75)
text(5.5, 43, "43", pos = 3, cex = 0.75)
text(6.5, 10, "10", pos = 3, cex = 0.75)
text(7.5, 22, "22", pos = 3, cex = 0.75)
text(9.5, 68, "68", pos = 3, cex = 0.75)
text(10.5, 31, "31", pos = 3, cex = 0.75)
text(11.5, 38, "38", pos = 3, cex = 0.75)
dev.off()
```
```{r}
jpeg(filename = "figures/monsoon/BGW18_Monsoon_Small.jpg",
     width=6.5,
     height=6.5,
     units="in",
     res=300)
## bottom, left, top, right
par(mar=c(5, 4, 4, 2))
barplot(BGW18groups, 
        col = c("#4472C4", "#ED7D31", "#FFC000"),
        main = "Boggy Creek Timelapse 2018",
        sub = "Number of Groups by Monsoonal Period",
        ylim = c(0,150),
        axes = FALSE,
        border = "black",
        beside = TRUE,
        legend = rownames(BGW18groups),
        font.axis = 3,
        font.lab = 2)
axis(2, at = seq(0, 150, by=10), labels = c(seq(0, 150, by=10)), cex.axis = 0.75, las = 2)
text(1.5, 21, "21", pos = 3, cex = 0.75)
text(2.5, 0, "0", pos = 3, cex = 0.75)
text(3.5, 39, "39", pos = 3, cex = 0.75)
text(5.5, 24, "24", pos = 3, cex = 0.75)
text(6.5, 1, "1", pos = 3, cex = 0.75)
text(7.5, 7, "7", pos = 3, cex = 0.75)
text(9.5, 29, "29", pos = 3, cex = 0.75)
text(10.5, 10, "10", pos = 3, cex = 0.75)
text(11.5, 11, "11", pos = 3, cex = 0.75)
dev.off()
```

```{r}
jpeg(filename = "figures/monsoon/WCS17_Monsoon_Small.jpg",
     width=6.5,
     height=6.5,
     units="in",
     res=300)
## bottom, left, top, right
par(mar=c(5, 4, 4, 2))
barplot(WCS17groups, 
        col = c("#4472C4", "#ED7D31", "#FFC000"),
        main = "Wildcat Creek Timelapse 2017",
        sub = "Number of Groups by Monsoonal Period",
        ylim = c(0,150),
        axes = FALSE,
        border = "black",
        beside = TRUE,
        legend = rownames(WCS17groups),
        font.axis = 3,
        font.lab = 2)
axis(2, at = seq(0, 150, by=10), labels = c(seq(0, 150, by=10)), cex.axis = 0.75, las = 2)
text(1.5, 131, "131", pos = 3, cex = 0.75)
text(2.5, 21, "21", pos = 3, cex = 0.75)
text(3.5, 52, "52", pos = 3, cex = 0.75)
text(5.5, 39, "39", pos = 3, cex = 0.75)
text(6.5, 26, "26", pos = 3, cex = 0.75)
text(7.5, 39, "39", pos = 3, cex = 0.75)
text(9.5, 48, "48", pos = 3, cex = 0.75)
text(10.5, 26, "26", pos = 3, cex = 0.75)
text(11.5, 44, "44", pos = 3, cex = 0.75)
dev.off()
```

```{r}
jpeg(filename = "figures/monsoon/WCS18_Monsoon_Small.jpg",
     width=6.5,
     height=6.5,
     units="in",
     res=300)
## bottom, left, top, right
par(mar=c(5, 4, 4, 2))
barplot(WCS18groups, 
        col = c("#4472C4", "#ED7D31", "#FFC000"),
        main = "Wildcat Creek Timelapse 2018",
        sub = "Number of Groups by Monsoonal Period",
        ylim = c(0,150),
        axes = FALSE,
        border = "black",
        beside = TRUE,
        legend = rownames(WCS18groups),
        font.axis = 3,
        font.lab = 2)
axis(2, at = seq(0, 150, by=10), labels = c(seq(0, 150, by=10)), cex.axis = 0.75, las = 2)
text(1.5, 77, "77", pos = 3, cex = 0.75)
text(2.5, 0, "0", pos = 3, cex = 0.75)
text(3.5, 41, "41", pos = 3, cex = 0.75)
text(5.5, 3, "3", pos = 3, cex = 0.75)
text(6.5, 0, "0", pos = 3, cex = 0.75)
text(7.5, 0, "0", pos = 3, cex = 0.75)
text(9.5, 17, "17", pos = 3, cex = 0.75)
text(10.5, 23, "23", pos = 3, cex = 0.75)
text(11.5, 32, "32", pos = 3, cex = 0.75)
dev.off()
```