# install the "pacman" package manager for installing and loading R packages
# install.packages("pacman")

# attach the "pacman" package for installing and loading R packages
require("pacman")

# Install and load required packages
pacman::p_load("usethis")
pacman::p_load("credentials")
pacman::p_load("tidyverse")
pacman::p_load("rmarkdown")
pacman::p_load("ggthemes")
pacman::p_load("jpeg")
pacman::p_load("viridis")
pacman::p_load("scales")
pacman::p_load("knitr")
pacman::p_load("lubridate")
pacman::p_load("magrittr")
# p_load("units") TODO need to install units dependencies in Docker container
pacman::p_load("stringi")
pacman::p_load("rio")
pacman::p_load("openxlsx")
pacman::p_load("Rcpp")
pacman::p_load("ggpubr")
pacman::p_load("rstatix")
pacman::p_load("XML")
pacman::p_load("methods")
pacman::p_load("tictoc")
pacman::p_load("openssl")
pacman::p_load("RPushbullet")
pacman::p_load("ggfittext")
pacman::p_load("ggsci")
pacman::p_load("effsize")
pacman::p_load("pwr")
pacman::p_load("hms")
pacman::p_load("styler")
pacman::p_load("lintr")
pacman::p_load("formatR")
pacman::p_load("RColorBrewer")
pacman::p_load("dlookr")
pacman::p_load("forcats")
pacman::p_load("glue")

# remotes::install_github("r-quantities/units")
# remotes::install_version("formatR", version = 1.12, repos = "https://cran.r-project.org/")
# remotes::install_github("mattcowgill/ggannotate")
# p_load("ggannotate")
