install.packages("pacman")
# attach the pacman library to manage loading or install the packages
require("pacman")

library("pacman")

# Commonly Used Packages
p_load("usethis")
p_load("gitcreds")
p_load("credentials")
p_load("ggplot2")
p_load("ggthemes")
p_load("dplyr")
p_load("tidyr")
p_load("jpeg")
p_load("viridis")
p_load("scales")
p_load("knitr")
p_load("lubridate")
p_load("magrittr")
p_load("readr")
p_load("stringr")
p_load("units")
p_load("tidyverse")
p_load("stringi")
p_load("beepr")
p_load("rio")
p_load("openxlsx")
p_load("Rcpp")
p_load("renv")
p_load("ggpubr")
p_load("rstatix")
p_load("forcats")
p_load("XML")
p_load("methods")
p_load("tictoc")
p_load("openssl")
p_load("RPushbullet")
p_load("ggfittext")
p_load("ggsci")
p_load("effsize")
p_load("pwr")
p_load("hms")
p_load("styler")
p_load("lintr")
p_load("formatR")
p_load("RColorBrewer")
p_load("dlookr")

# remotes::install_github("r-quantities/units")
# remotes::install_version("formatR", version = 1.12, repos = "https://cran.r-project.org/")
# remotes::install_github("mattcowgill/ggannotate")
# p_load("ggannotate")
