---
title: "Stubble Height"
author: "Andrew Antaya"
date: "June 20, 2019"
output: html_notebook
---

```{r}
# clear the environment
rm(list=ls(all=TRUE))
```

```{r}
source("packages.R")
```

```{r}
source("functions.R")
```

```{r}
## read in data
BGW17stubble <- readr::read_csv('data/vegetation/white-mountains/2017-boggy-stubble-height.csv',
                                col_names = TRUE, 
                                na = c(""," ","NA"))
WCS17stubble <- readr::read_csv('data/vegetation/white-mountains/2017-wildcat-stubble-height.csv',
                                col_names = TRUE,
                                na = c(""," ","NA"))
BGW18stubble <- readr::read_csv('data/vegetation/white-mountains/2018-boggy-stubble-height.csv', 
                                col_names = TRUE, 
                                na = c(""," ","NA"))
WCS18stubble <- readr::read_csv('data/vegetation/white-mountains/2018-wildcat-stubble-height.csv',
                                col_names = TRUE, 
                                na = c(""," ","NA"))

stubble_data <- bind_rows(BGW17stubble, WCS17stubble, BGW18stubble, WCS18stubble)

print(stubble_data)
```
We have 1 missing height value in the data that we need to remove.
```{r}
## clean up the data by removing any missing values
stubble_data <- stubble_data %>% tidyr::drop_na("Height-in")

print(stubble_data)
```
```{r}
stubble_data$Species <- stubble_data %>% pull(Species) %>% forcats::as_factor()

stubble_data$Species <- stubble_data %>% pull(Species) %>% fct_explicit_na(na_level = "Missing")

stubble_data
```

Plot a histogram of Kentucky bluegrass to visualize the distribution of stubble heights. 
```{r Boggy 2017 Histogram}
# Boggy 2017
stubble_data %>% 
        dplyr::filter(Site == "Boggy" & Year == "2017") %>% 
        dplyr::filter(Species == "POPR") %>% 
        pull("Height-in") %>% 
        hist(breaks = seq(0, 10, by = 1), 
             axes = FALSE,
             main = "Frequency Count of Poa Pratensis (Kentucky Bluegrass)",
             xlab = "Stubble Height (in)",
             xlim = c(0, 10),
             ylim = c(0, 100))
axis(1, at = seq(0, 10, by = 1), 
     labels = seq(0, 10, by = 1), 
     cex.axis= 0.75, las = 2)
axis(2, at = seq(0, 100, by = 10), 
     labels = seq(0, 100, by = 10), 
     cex.axis= 0.75, las = 2)
mtext("Boggy 2017", 3, adj = 0.5, line = -1)
```

```{r Wildcat 2017 Histogram}
# Wildcat 2017
stubble_data %>% 
        dplyr::filter(Site == "Wildcat" & Year == "2017") %>% 
        dplyr::filter(Species == "POPR") %>% 
        pull("Height-in") %>% 
        hist(breaks = seq(0, 10, by = 1), 
             axes = FALSE,
             main = "Frequency Count of Poa Pratensis (Kentucky Bluegrass)",
             xlab = "Stubble Height (in)",
             xlim = c(0, 10),
             ylim = c(0, 100))
axis(1, at = seq(0, 10, by = 1), 
     labels = seq(0, 10, by = 1), 
     cex.axis= 0.75, las = 2)
axis(2, at = seq(0, 100, by = 10), 
     labels = seq(0, 100, by = 10), 
     cex.axis= 0.75, las = 2)
mtext("Wildcat 2017", 3, adj = 0.5, line = -1)
```
Get the mean, standard deviation, standard error for the stubble height data.
```{r}
BGW17stubblestats <- stubble_data %>% 
  dplyr::filter(Site == "Boggy" & Year == 2017) %>% 
        group_by(Species) %>% 
        rstatix::get_summary_stats("Height-in", type = "common")

BGW18stubblestats <- stubble_data %>% 
  dplyr::filter(Site == "Boggy" & Year == 2018) %>% 
        group_by(Species) %>% 
        rstatix::get_summary_stats("Height-in", type = "common")

WCS17stubblestats <- stubble_data %>% 
  dplyr::filter(Site == "Wildcat" & Year == 2017) %>% 
        group_by(Species) %>% 
        rstatix::get_summary_stats("Height-in", type = "common")

WCS18stubblestats <- stubble_data %>% 
  dplyr::filter(Site == "Wildcat" & Year == 2018) %>% 
        group_by(Species) %>% 
        rstatix::get_summary_stats("Height-in", type = "common")

BGW17stubblestats
BGW18stubblestats
WCS17stubblestats
WCS18stubblestats
```
Rearrange the order of the species count, descending from highest count to lowest count.
```{r}
BGW17stubblestats <- BGW17stubblestats %>% dplyr::arrange(desc(n))

WCS17stubblestats <-WCS17stubblestats %>% dplyr::arrange(desc(n))

BGW17stubblestats
WCS17stubblestats
```
Take the top 3 species for each site. 
```{r}
BGW17stubblestats_top3 <- BGW17stubblestats %>% dplyr::slice(1:3)

BGW17stubblestats_top3
```

```{r Boggy 2017 Stubble Height Figure}
ggplot(BGW17stubblestats_top3, aes(fill = Species, y = mean, x = Species)) +
  geom_col(width = 0.75) +
  scale_fill_discrete(name = "Species", labels = c("Poa pratensis", "Carex sp.", "Poa fendleriana")) +
  labs(title = "Boggy Creek Stubble Height", subtitle = "2017") +
  ylab(expression(paste("Subble Height", " ", "(Inch)", " ± SE"))) +
  scale_y_continuous(limits = c(0, 5)) +
  geom_errorbar(aes(ymin = (mean-se), ymax = (mean+se)), position = position_dodge(0.5), width = 0.25) +
  theme(plot.title = element_text(hjust = 0.5),
        plot.subtitle = element_text(hjust = 0.5),
        axis.text.x = element_text(margin = margin(t = 0, r = 0, b = 10, l = 0)),
        axis.text.y = element_text(margin = margin(t = 0, r = 0, b = 0, l = 10))) +

  # add stubble height values above the  error bars
  # round the mean stubble height value using significant figures
  annotate(geom = "text", x = 1, y = 3.5, label = signif(BGW17stubblestats_top3$mean[1], 2)) +
  annotate(geom = "text", x = 2, y = 4.75, label = signif(BGW17stubblestats_top3$mean[2], 2)) +
  annotate(geom = "text", x = 3, y = 4, label = signif(BGW17stubblestats_top3$mean[3], 2))

ggsave("Boggy-2017-Stubble-Height.jpg", 
    path = paste0(getwd(),"/figures", "/stubbleheight"))
```

```{r Wildcat 2017 Stubble Height Figure}
ggplot(WCS17stubblestats, aes(fill = Species, y = mean, x = Species)) +
  geom_col(width = 0.75) +
  scale_fill_discrete(name = "Species", labels = c("Poa pratensis", "Carex sp.", "Poa fendleriana")) +
  labs(title = "Wildcat Creek Stubble Height", subtitle = "2017") +
  ylab(expression(paste("Subble Height", " ", "(Inch)", " ± SE"))) +
  scale_y_continuous(limits = c(0, 5)) +
  geom_errorbar(aes(ymin = (mean-se), ymax = (mean+se)), position = position_dodge(0.5), width = 0.25) +
  theme(plot.title = element_text(hjust = 0.5),
        plot.subtitle = element_text(hjust = 0.5),
        axis.text.x = element_text(margin = margin(t = 0, r = 0, b = 10, l = 0)),
        axis.text.y = element_text(margin = margin(t = 0, r = 0, b = 0, l = 5))) +

  # add stubble height values above the  error bars
  # round the mean stubble height value using significant figures
  annotate(geom = "text", x = 1, y = 1.5, label = signif(WCS17stubblestats$mean[1], 2)) +
  annotate(geom = "text", x = 2, y = 4.5, label = signif(WCS17stubblestats$mean[2], 2)) +
  annotate(geom = "text", x = 3, y = 1.5, label = signif(WCS17stubblestats$mean[3], 2))

ggsave("Wildcat-2017-Stubble-Height.jpg", 
path = paste0(getwd(),"/figures", "/stubbleheight"))
```

```{r Boggy 2018 Stubble Height Figure}
ggplot(BGW18stubblestats, aes(fill = Species, y = mean, x = Species)) +
  geom_col(width = 0.25) +
  labs(title = "Boggy Creek Stubble Height", subtitle = "2018") +
  ylab(expression(paste("Subble Height", " ", "(Inch)", " ± SE"))) +
  scale_y_continuous(limits = c(0, 5)) +
  geom_errorbar(aes(ymin = (mean-se), ymax = (mean+se)), position = position_dodge(0.5), width = 0.1) +
  theme(plot.title = element_text(hjust = 0.5),
        plot.subtitle = element_text(hjust = 0.5),
        axis.text.x = element_text(margin = margin(t = 0, r = 0, b = 10, l = 0)),
        axis.text.y = element_text(margin = margin(t = 0, r = 0, b = 0, l = 10))) +
  # add stubble height values above the  error bars
  # round the mean stubble height value using significant figures
  annotate(geom = "text", x = 1, y = 3.25, label = signif(BGW18stubblestats$mean[1], 2))
ggsave("Boggy-2018-Stubble-Height.jpg", 
    path = paste0(getwd(),"/figures", "/stubbleheight"))
```

```{r Wildcat 2018 Stubble Height Figure}
ggplot(WCS18stubblestats, aes(fill = Species, y = mean, x = Species)) +
  geom_col(width = 0.25) +
  labs(title = "Wildcat Creek Stubble Height", subtitle = "2018") +
  ylab(expression(paste("Subble Height", " ", "(Inch)", " ± SE"))) +
  scale_y_continuous(limits = c(0, 5)) +
  geom_errorbar(aes(ymin = (mean-se), ymax = (mean+se)), position = position_dodge(0.5), width = 0.1) +
  theme(plot.title = element_text(hjust = 0.5),
        plot.subtitle = element_text(hjust = 0.5),
        axis.text.x = element_text(margin = margin(t = 0, r = 0, b = 10, l = 0)),
        axis.text.y = element_text(margin = margin(t = 0, r = 0, b = 0, l = 10))) +
  # add stubble height values above the  error bars
  # round the mean stubble height value using significant figures
  annotate(geom = "text", x = 1, y = 4.25, label = signif(WCS18stubblestats$mean[1], 2))
ggsave("Wildcat-2018-Stubble-Height.jpg", 
    path = paste0(getwd(),"/figures", "/stubbleheight"))
```

```{r}

```

