---
title: "R Notebook"
output: html_notebook
---

Clear the R environment to start from a clean slate.

```{r}
# clear the environment
rm(list=ls(all=TRUE))
```

```{r}
source("packages.R")
```

```{r}
source("functions.R")
```

```{r include=FALSE}
source_rmd("production.Rmd")
```

```{r}
print(production)
print(residual)
```

Calculate the summary statistics for each site and year. This method is slightly different from the previous method, instead of grouping by year, each site-year (e.g., Boggy 2017) has summary statistics generated and stored into a object. Then those objects are bound together into a data frame.

```{r}
residual_stats <- NULL

BGW17 <- residual %>% 
  dplyr::filter(Site == "Boggy" & Year == 2017) %>% 
  rstatix::get_summary_stats(lb_acre, type = "common")
BGW18 <- residual %>% 
  dplyr::filter(Site == "Boggy" & Year == 2018) %>% 
  rstatix::get_summary_stats(lb_acre, type = "common")
BGW19 <- residual %>% 
  dplyr::filter(Site == "Boggy" & Year == 2019) %>% 
  rstatix::get_summary_stats(lb_acre, type = "common")
WCS17 <- residual %>% 
  dplyr::filter(Site == "Wildcat" & Year == 2017) %>% 
  rstatix::get_summary_stats(lb_acre, type = "common")
WCS18 <- residual %>% 
  dplyr::filter(Site == "Wildcat" & Year == 2018) %>% 
  rstatix::get_summary_stats(lb_acre, type = "common")
WCS19 <- residual %>% 
  dplyr::filter(Site == "Wildcat" & Year == 2019) %>% 
  rstatix::get_summary_stats(lb_acre, type = "common")

residual_stats <- residual_stats %>% bind_rows(BGW17, BGW18, BGW19, WCS17, WCS18, WCS19)

# add the site names to the data frame 
residual_stats <- residual_stats %>% 
  add_column(site = c("BGW17", "BGW18", "BGW19", "WCS17", "WCS18", "WCS19"), .before = 1)

print(residual_stats)
```

```{r}
print(production_stats)
```
```{r}
residual_stats$min <- as.numeric(residual_stats$min) 
residual_stats$max <- as.numeric(residual_stats$max)
residual_stats$median <- as.numeric(residual_stats$median)
residual_stats$mean <- as.numeric(residual_stats$mean)

print(residual_stats)
```

```{r}
percent_utilization <- (production_stats$mean - residual_stats$mean) / production_stats$mean

utilization <- percent_utilization * 100

utilization <- round(utilization)

print(utilization)
```
```{r}
veg_data <- dplyr::bind_rows(production_stats, residual_stats)

veg_data <- veg_data %>% tibble::add_column(Type = c(rep("Production", 6), rep("Availability", 6)), .after = "site")

print(veg_data)
```
```{r}
veg_data$Type <- veg_data$Type %>% fct_inorder()

print(veg_data)
```

```{r}
excel_colors <- c(rep("#4472C4", 3), rep("#ED7D31", 3))
```

```{r}
production_stats$mean - production_stats$se
production_stats$mean + production_stats$se
```
```{r}
residual_stats$mean - residual_stats$se
residual_stats$mean + residual_stats$se
```

```{r}
ggplot(veg_data, aes(fill = Type, y = mean, x = site)) +
  geom_col(width = 0.7, position = position_dodge(0.7)) +
  labs(title = "White Mountains Vegetation Utilization", subtitle = "2017-2019") +
  ylab(expression(paste("Pounds ", "Acre"^"-1", " ± SE"))) + 
  xlab("Percent Utilization") +
  scale_y_continuous(limits = c(-500,6000), breaks = c(seq(1000, 5000, by = 1000))) +
  geom_errorbar(aes(ymin = (mean-se), ymax = (mean+se)), position = position_dodge(0.7), width = 0.25) +
  theme(plot.title = element_text(hjust = 0.5),
        plot.subtitle = element_text(hjust = 0.5),
        axis.text.x = element_text(margin = margin(t = 5, r = 0, b = 10, l = 0)),
        axis.ticks.x.bottom = element_blank()) +
  annotate(geom = "text", x = 1, y = -500, label = paste0(utilization[1], "%")) +
  annotate(geom = "text", x = 2, y = -500, label = paste0(utilization[2], "%")) +
  annotate(geom = "text", x = 3, y = -500, label = paste0(utilization[3], "%")) +
  annotate(geom = "text", x = 4, y = -500, label = paste0(utilization[4], "%")) +
  annotate(geom = "text", x = 5, y = -500, label = paste0(utilization[5], "%")) +
  annotate(geom = "text", x = 6, y = -500, label = paste0(utilization[6], "%"))
  
ggsave("Utilization-Across-Year-Comparison-Values-Under-Bars-Adjust-Center.jpg", 
    path = paste0(getwd(),"/figures", "/utilization"))
```

