---
title: "PhotoChunk"
author: "Brandon Mayer"
date: "1/21/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)

```
List of files of sorted files to be chunked for scoring. Will target all files for the year of interest. 
```{r}
#Folder of sorted photos from the first Txt2Consolidate processing step. Readline for efficiency. 
#MainFolder <- gsub("\\\\", "/", readline())
MainFolder <- "F:/CameraProject"
Year <- readline()
Files_to_Chunk<- list.files(MainFolder, pattern = paste0(Year,"_sorted"),recursive = T,include.dirs = T,full.names = T) 
Files_Chunked <- Files_to_Chunk[grepl('_Analysis_2020', Files_to_Chunk)]
Files_Chunked <- Files_Chunked[!grepl('.csv', Files_Chunked)]
Files_to_Chunk <- data.frame(Files_to_Chunk[!grepl('_Analysis_2020', Files_to_Chunk)])
n<- length(str_split(string = Files_Chunked,pattern =  "/")[[1]])
Files_Chunked <- str_split_fixed(string = Files_Chunked,pattern =  "/",n = n)[,n]
n <- length(str_split(string = Files_Chunked,pattern =  "_")[[1]])-1
pat <- paste0('^([^_]+(?:_[^_]+){',n-1,'}).*')
(Files_Chunked <- c(sub(pat, '\\1', Files_Chunked)))
(Files_to_Chunk <- Files_to_Chunk[!grepl(paste(Files_Chunked, collapse="|"), Files_to_Chunk[[1]]),])
```

Photo chunking. 
Takes folders of previously sorted photos and breaks them into manageable chunks. If you have the folders, this will automatically create a folder in the drive the photos are stored. 

```{r cars}


for (h in seq_along(Files_to_Chunk)) {
  n <- length(str_split(Files_to_Chunk[h], pattern = "/")[[1]])
  site <- str_split(str_split_fixed(Files_to_Chunk[h],pattern = "/", n=n)[n],pattern = "_")[[1]][1]
  year <- str_sub(str_split(str_split_fixed(Files_to_Chunk[h],pattern = "/", n=n)[5],pattern = "_")[[1]][3],-4,-1)
  # Create final folder to dump chunked folders
  #               **Keep the same once location is set** **Change this depending on site**
  final_dir <- paste(MainFolder,"/Chunked_folders/",site,"_Analysis_",year, sep = "") 
  dir.create(final_dir)

  # After creating a folder to store the chunks you just need to reenter 
  # each "sorted" folder in succession at "line 21". You could make a for-loop with the same chunk size
  # set for each chunk, but this would leave a small chunk with the remaining photos. I figured 
  # keeping size the same throughout a collection period would be better for planning. 

  # Source file to chunk
  file_source <- basename(Files_to_Chunk[h]) #"JCY_09082019_11082019_sorted"
  source_dir <- dirname(Files_to_Chunk[h])

  # Breakdown of Chunking parameters
  # To_sort <- read_csv(source_csv)
  To_sort <- data.frame("files"= list.files(Files_to_Chunk[h],full.names = T))
  nr <- nrow(To_sort)
  if (nr/2<500) {
    chunk <-nr  
    }else if (nr/2<800) {
      chunk <- nr/2
      }else{
        chunk <-nr/3  
        }
  # Actual Chunking of csv into a list of chunks
  r  <- rep(1:ceiling(nr/chunk),each=chunk)[1:nr]
  d <- split(To_sort,r)
  dir_source_comb <- paste(final_dir,file_source, sep = "/")
  for (i in 1:length(d)){
    x <- paste(dir_source_comb, i, sep = "_")
    dir.create(x)
    photo_list_path <-  data.frame(d[[i]])
    for(j in photo_list_path){
      file.copy(j,x)
    }
  }
}

FilesToBeCSVd<- list.files("F:/CameraProject", pattern = "2020_sorted_",recursive = T,include.dirs = T,full.names = T)
(FilesToBeCSVd <- FilesToBeCSVd[!grepl('.csv', FilesToBeCSVd)])
FilesToBeCSVd <- FilesToBeCSVd[!grepl('vids', FilesToBeCSVd)]


```
Add CSV of filenames for sorting with the script below

```{r pressure, echo=FALSE}
# library(lubridate)

#________________________________________________________________________________________________________________________-
# 

for (i in FilesToBeCSVd) {
  ## R SCRIPT
  ## get the current directory, if this script was copied into the image storage folder, then
  ## the working directory is that folder.

  
  ## make a list of all the JPEGs in the file, if images are stored in some other format, update the code below
  imagefiles<-list.files(path=i,full.names=T,pattern=c(".JPG|.jpg"),include.dirs = T,recursive=T)
  
  ## create a data.frame from the list of all image files and extract metadata associated with each image	
  imagefilesinfo<-as.data.frame(do.call("rbind",lapply(imagefiles,file.info)))
  imagefilesinfo<-imagefilesinfo[,c("size","mtime")]
  imagefilesinfo$ImagePath<-imagefiles
  imagefilesinfo$ImageRelative<-do.call("rbind",lapply(strsplit(imagefiles,split=paste(i,"/",sep="")),rev))[,1]
  imagefilesinfo$ImageFilename<-do.call("rbind",lapply(strsplit(imagefiles,split="/"),rev))[,1]
  imagefilesinfo$ImageTime<-gsub("[[:space:]]", "",substr(as.character(imagefilesinfo$mtime),regexpr(":",imagefilesinfo$mtime)-2,regexpr(":",imagefilesinfo$mtime)+5))
  imagefilesinfo$ImageDate<-gsub("[[:space:]]", "",substr(as.character(imagefilesinfo$mtime),1,10))
  imagefilesinfo$RecordNumber<-seq(1:length(imagefilesinfo$ImagePath))
  imagefilesinfo$ImageSize<-as.numeric(imagefilesinfo$size)
  imagefilesinfo<-imagefilesinfo[,c(8,5,3,4,9,6,7)]
  
  #remove images of size 0 - some cameras have image write-errors that cannot be processed
  imagefilesinfo<-imagefilesinfo[imagefilesinfo$ImageSize!=0,]
  
  # ## OPTIONAL - DEFINE A SUBSET OF IMAGES TO PROCESS BASED ON A REGULAR TIME SCHEDULE
  # #Make list of images to include by listing all years wanted (must be four-digit years: 2015,2016,...)
  # useyears = c("2012","2013","2014","2015","2016","2017")
  # #Make list of images to include by listing all months wanted (quotes are necessary as it must be two-digit months: c("01","02",...))
  # usemonths = c("01","02","03","04","05","06","07","08","09","10","11","12")
  # #Make list of images to include by listing all days of the month wanted (must be two-digit days: 01,02,...)
  # usedays = c("01","02","03","04","05","06","07","08","09","10","11","12","13","14","15","16","17","18","19","20","21","22","23","24","25","26","27","28","29","30","31")
  # #Make list of images to include by listing all hous of the day wanted (must be two-digit hours: 01,02,...)
  # usehours = c("00","01","02","03","04","05","06","07","08","09","10","11","12","13","14","15","16","17","18","19","20","21","22","23")
  # #Now subset the list of all images to just those matching the time criteria above
  # imagefilesinfo<-imagefilesinfo[which(substr(imagefilesinfo$ImageDate,1,4) %in% useyears &
  #                                        substr(imagefilesinfo$ImageDate,6,7) %in% usemonths &
  #                                        substr(imagefilesinfo$ImageDate,9,10) %in% usedays &
  #                                        substr(imagefilesinfo$ImageTime,1,2) %in% usehours),]
  
  ## OPTIONAL - SET A TIME FOR A CUSTOM ALERT MESSAGE TO DISPLAY ON THE EXCEL FORM
  # set an alert based on time or date, These images will all be included but the 'ImageAlert' will be set to True. If no Alert is Desired, set Alert=F.
  # when an alert is set, a custom message can be defined to 'pop-up' on the excel form for every image with Altert set to TRUE.
  # this feature is nice for reminding the user to record certain data types that are not necessarily recorded for every image (e.g. temperature)
  # by default all years, months, days of the month, hours of the day, and minutes of the hour are listed for alerts which would slow down data entry
  # as it would post the alert message on every image
  Alert=FALSE
  
  # If an alert is desired:
  #Make list of images to alert by listing all years when alerts are wanted (must be four-digit years: 2015,2016,...)
  alertyears = as.character(c(2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020))
  #Make list of images to alert by listing all months when alerts are wanted (quotes are necessary as it must be two-digit months: c("01","02",...))
  alertmonths = c("01","02","03","04","05","06","07","08","09","10","11","12")
  #Make list of images to alert by listing all days of the month when alerts are wanted (must be two-digit days: 01,02,...)
  alertdays = c("01","02","03","04","05","06","07","08","09","10","11","12","13","14","15","16","17","18","19","20","21","22","23","24","25","26","27","28","29","30","31")
  #Make list of images to alert by listing all hours of the day when alerts are wanted (must be two-digit hours: 01,02,...)
  alerthours = c("06","15")
  #Make list of images to alert by listing all minutes of the hour wanted (must be two-digit minutes: 01,02,...)
  alertminutes = c("00")
  # this code will set the ImageAlert to "TRUE" for all images matching the above specified time conditions
  if (Alert==T){
    imagefilesinfo$ImageAlert <- c(substr(imagefilesinfo$ImageDate,1,4) %in% alertyears & 
                                     substr(imagefilesinfo$ImageDate,6,7) %in% alertmonths & 
                                     substr(imagefilesinfo$ImageDate,9,10) %in% alertdays & 
                                     substr(imagefilesinfo$ImageTime,1,2) %in% alerthours & 
                                     substr(imagefilesinfo$ImageTime,4,5) %in% alertminutes)
  } else {
    imagefilesinfo$ImageAlert<- FALSE
  }
  
  ## write a .csv file named after the working directory containing the image data.  All the data from this .csv file should be copied into the 
  ## Excel form.  The .csv file will show up in the same directory as this script once this script is run.
  
  excelfilename<-paste(i,'/',rev(strsplit(i,split="/")[[1]])[1],".csv",sep="")
  write.csv(imagefilesinfo,excelfilename,row.names=F)
}
```

