---
title: "R Notebook"
output: html_notebook
---
White Mountain Sites
Boggy and Wildcat Creek Grazed Sites
Production and Utilization calculations
02/07/2019
Written by Andrew Antaya

```{r}
library("ggplot2", lib.loc="~/R/win-library/3.5")
library("dplyr", lib.loc="~/R/win-library/3.5")
library("jpeg", lib.loc="~/R/win-library/3.5")

#source_rmd("functions.Rmd")

## read in data
mydata <- read.csv('data/vegetation/White Mountain Production 2017-2018.csv')
mydata

## select the 2017 Boggy Grazed values
BGW17G <- mydata[28:32, ]

## select the 2017 Boggy Exclosure values
BGW17E <- mydata[23:27, ]

## select the 2017 Wildcat Grazed values
WCS17G <- mydata[38:42, ]

## select the 2017 Wildcat Exclosure values
WCS17E <- mydata[33:37, ]

## select the 2018 Boggy Grazed values
BGW18G <- mydata[7:11, ]

## select the 2018 Boggy Exclosure values
BGW18E <- mydata[1:6, ]

## select the 2018 Wildcat Grazed values
WCS18G <- mydata[18:22, ]

## select the 2018 Wildcat Exclosure values
WCS18E <- mydata[12:17, ]
```

```{r}
## create empty table to store mean, standard deviation, standard error, 95% confidence interval
mystats<- data.frame(sites=c("BGW17E", "BGW17G", "WCS17E", "WCS17G", "BGW18E", "BGW18G",  "WCS18E", "WCS18G"))

## calculate mean production values for each year and site (g/m2)
mystats[1, 2] <- mean(BGW17E$TotalDry)
mystats[2, 2] <- mean(BGW17G$TotalDry)
mystats[3, 2] <- mean(WCS17E$TotalDry)
mystats[4, 2] <- mean(WCS17G$TotalDry)
mystats[5, 2] <- mean(BGW18E$TotalDry)
mystats[6, 2] <- mean(BGW18G$TotalDry)
mystats[7, 2] <- mean(WCS18E$TotalDry)
mystats[8, 2] <- mean(WCS18G$TotalDry)

## convert mean production values from g/m2 to kg/ha by *10
mystats[1, 3] <- 10*mean(BGW17E$TotalDry)
mystats[2, 3] <- 10*mean(BGW17G$TotalDry)
mystats[3, 3] <- 10*mean(WCS17E$TotalDry)
mystats[4, 3] <- 10*mean(WCS17G$TotalDry)
mystats[5, 3] <- 10*mean(BGW18E$TotalDry)
mystats[6, 3] <- 10*mean(BGW18G$TotalDry)
mystats[7, 3] <- 10*mean(WCS18E$TotalDry)
mystats[8, 3] <- 10*mean(WCS18G$TotalDry)

## convert mean production values from g/m2 to lbs/acre
mystats[1, 4] <- 8.92179*mean(BGW17E$TotalDry)
mystats[2, 4] <- 8.92179*mean(BGW17G$TotalDry)
mystats[3, 4] <- 8.92179*mean(WCS17E$TotalDry)
mystats[4, 4] <- 8.92179*mean(WCS17G$TotalDry)
mystats[5, 4] <- 8.92179*mean(BGW18E$TotalDry)
mystats[6, 4] <- 8.92179*mean(BGW18G$TotalDry)
mystats[7, 4] <- 8.92179*mean(WCS18E$TotalDry)
mystats[8, 4] <- 8.92179*mean(WCS18G$TotalDry)

## standard deviation SD
mystats[1, 5] <- 8.92179*sd(BGW17E$TotalDry)
mystats[2, 5] <- 8.92179*sd(BGW17G$TotalDry)
mystats[3, 5] <- 8.92179*sd(WCS17E$TotalDry)
mystats[4, 5] <- 8.92179*sd(WCS17G$TotalDry)
mystats[5, 5] <- 8.92179*sd(BGW18E$TotalDry)
mystats[6, 5] <- 8.92179*sd(BGW18G$TotalDry)
mystats[7, 5] <- 8.92179*sd(WCS18E$TotalDry)
mystats[8, 5] <- 8.92179*sd(WCS18G$TotalDry)

mystats[1, 6] <- 8.92179*se(BGW17E$TotalDry)
mystats[2, 6] <- 8.92179*se(BGW17G$TotalDry)
mystats[3, 6] <- 8.92179*se(WCS17E$TotalDry)
mystats[4, 6] <- 8.92179*se(WCS17G$TotalDry)
mystats[5, 6] <- 8.92179*se(BGW18E$TotalDry)
mystats[6, 6] <- 8.92179*se(BGW18G$TotalDry)
mystats[7, 6] <- 8.92179*se(WCS18E$TotalDry)
mystats[8, 6] <- 8.92179*se(WCS18G$TotalDry)

## Lower 95% confidence intervals of the production mean 
mystats[1, 7] <- 8.92179*(mean(BGW17E$TotalDry)-2.571*se(BGW17E$TotalDry))
mystats[2, 7] <- 8.92179*(mean(BGW17G$TotalDry)-2.571*se(BGW17G$TotalDry))
mystats[3, 7] <- 8.92179*(mean(WCS17E$TotalDry)-2.571*se(WCS17E$TotalDry))
mystats[4, 7] <- 8.92179*(mean(WCS17G$TotalDry)-2.571*se(WCS17G$TotalDry))
mystats[5, 7] <- 8.92179*(mean(BGW18E$TotalDry)-2.571*se(BGW18E$TotalDry))
mystats[6, 7] <- 8.92179*(mean(BGW18G$TotalDry)-2.571*se(BGW18G$TotalDry))
mystats[7, 7] <- 8.92179*(mean(WCS18E$TotalDry)-2.571*se(WCS18E$TotalDry))
mystats[8, 7] <- 8.92179*(mean(WCS18G$TotalDry)-2.571*se(WCS18G$TotalDry))

## Upper 95% confidence intervals of the production mean
mystats[1, 8] <- 8.92179*(mean(BGW17E$TotalDry)+2.571*se(BGW17E$TotalDry))
mystats[2, 8] <- 8.92179*(mean(BGW17G$TotalDry)+2.571*se(BGW17G$TotalDry))
mystats[3, 8] <- 8.92179*(mean(WCS17E$TotalDry)+2.571*se(WCS17E$TotalDry))
mystats[4, 8] <- 8.92179*(mean(WCS17G$TotalDry)+2.571*se(WCS17G$TotalDry))
mystats[5, 8] <- 8.92179*(mean(BGW18E$TotalDry)+2.571*se(BGW18E$TotalDry))
mystats[6, 8] <- 8.92179*(mean(BGW18G$TotalDry)+2.571*se(BGW18G$TotalDry))
mystats[7, 8] <- 8.92179*(mean(WCS18E$TotalDry)+2.571*se(WCS18E$TotalDry))
mystats[8, 8] <- 8.92179*(mean(WCS18G$TotalDry)+2.571*se(WCS18G$TotalDry))

## add column names to the dataframe used to organize
colnames(mystats) <- c("sites", "prod_g_m2", "prod_kg_ha", "prod_lbs_acre", "SD", "SE", "L95%CI", "U95%CI")

mystats
```
```{r}
BGW17prod <- data.frame(BGW17 = c("Ungrazed", "Grazed"), production = c(mystats[1,4], mystats[2,4]))
BGW17prod
BGW18prod <- data.frame(BGW18 = c("Ungrazed", "Grazed"), production = c(mystats[5,4], mystats[6,4]))
BGW18prod
WCS17prod <- data.frame(WCS17 = c("Ungrazed", "Grazed"), production = c(mystats[3,4], mystats[4,4]))
WCS17prod
WCS18prod <- data.frame(WCS18 = c("Ungrazed", "Grazed"), production = c(mystats[7,4], mystats[8,4]))
WCS18prod
```


```{r}
jpeg(filename = "figures/vegetation/Boggy_Creek_Production_2017.jpg",
     width=3.2,
     height=3.2,
     units="in",
     res=300)
plot.new()
# bottom, left, top, right
par(mar=c(2, 4, 2, 2))
barplot(BGW17prod$production,
        col = c("#404788FF", "#FDE725FF"),
        main = "Boggy Creek Production 2017",
        axes = FALSE,
        names.arg=(c("Production", "Availability")),
        ylab = expression(paste("lbs ", "acre"^"-1", " ± SE")),
        cex.lab = 1,
        cex.main = 1,
        ylim = c(0, 6500))
axis(2,at=c(seq(0,6500,1000)),labels=c(seq(0,6500,1000)), cex.axis= 0.5, las = 2)
segments(0.7, mystats[1, 4] - mystats[1, 6], 0.7,
         mystats[1, 4] + mystats[1, 6], lwd = 1)
arrows(0.7, mystats[1, 4] - mystats[1, 6], 0.7,
       mystats[1, 4] + mystats[1, 6], lwd = 1, angle = 90,
       code = 3, length = 0.05)
segments(1.9, mystats[2, 4] - mystats[2, 6], 1.9,
         mystats[2, 4] + mystats[2, 6], lwd = 1)
arrows(1.9, mystats[2, 4] - mystats[2, 6], 1.9,
       mystats[2, 4] + mystats[2, 6], lwd = 1, angle = 90,
       code = 3, length = 0.05)
text(0.7, 5700, "4705", pos = 3, cex = 0.75)
text(1.9, 750, "598", pos = 3, cex = 0.75)
dev.off()
```

```{r}
jpeg(filename = "figures/vegetation/Boggy_Creek_Production_2018.jpg",
     width=3.2,
     height=3.2,
     units="in",
     res=300)
plot.new()
# bottom, left, top, right
par(mar=c(2, 4, 2, 2))
barplot(BGW18prod$production,
        col = c("#404788FF", "#FDE725FF"),
        main = "Boggy Creek Production 2018",
        axes = FALSE,
        names.arg=(c("Production", "Availability")),
        ylab = expression(paste("lbs ", "acre"^"-1", " ± SE")),
        cex.lab = 1,
        cex.main = 1,
        ylim = c(0, 6500))
axis(2,at=c(seq(0,6500,1000)),labels=c(seq(0,6500,1000)), cex.axis= 0.5, las = 2)
segments(0.7, mystats[5, 4] - mystats[5, 6], 0.7,
         mystats[5, 4] + mystats[5, 6], lwd = 1)
arrows(0.7, mystats[5, 4] - mystats[5, 6], 0.7,
       mystats[5, 4] + mystats[5, 6], lwd = 1, angle = 90,
       code = 3, length = 0.05)
segments(1.9, mystats[6, 4] - mystats[6, 6], 1.9,
         mystats[6, 4] + mystats[6, 6], lwd = 1)
arrows(1.9, mystats[6, 4] - mystats[6, 6], 1.9,
       mystats[6, 4] + mystats[6, 6], lwd = 1, angle = 90,
       code = 3, length = 0.05)
text(0.7, 4200, "3483", pos = 3, cex = 0.75)
text(1.9, 125, "93.9", pos = 3, cex = 0.75)
dev.off()
```

```{r}
jpeg(filename = "figures/vegetation/Wildcat_Creek_Production_2017.jpg",
     width=3.2,
     height=3.2,
     units="in",
     res=300)
plot.new()
# bottom, left, top, right
par(mar=c(2, 4, 2, 2))
barplot(WCS17prod$production,
        col = c("#404788FF", "#FDE725FF"),
        main = "Wildcat Creek Production 2017",
        axes = FALSE,
        names.arg=(c("Production", "Availability")),
        ylab = expression(paste("lbs ", "acre"^"-1", " ± SE")),
        cex.lab = 1,
        cex.main = 1,
        ylim = c(0, 6500))
axis(2,at=c(seq(0,6500,1000)),labels=c(seq(0,6500,1000)), cex.axis= 0.5, las = 2)
segments(0.7, mystats[3, 4] - mystats[3, 6], 0.7,
         mystats[3, 4] + mystats[3, 6], lwd = 1)
arrows(0.7, mystats[3, 4] - mystats[3, 6], 0.7,
       mystats[3, 4] + mystats[3, 6], lwd = 1, angle = 90,
       code = 3, length = 0.05)
segments(1.9, mystats[4, 4] - mystats[4, 6], 1.9,
         mystats[4, 4] + mystats[4, 6], lwd = 1)
arrows(1.9, mystats[4, 4] - mystats[4, 6], 1.9,
       mystats[4, 4] + mystats[4, 6], lwd = 1, angle = 90,
       code = 3, length = 0.05)
text(0.7, 5500, "4766", pos = 3, cex = 0.75)
text(1.9, 600, "457", pos = 3, cex = 0.75)
dev.off()
```

```{r}
jpeg(filename = "figures/vegetation/Wildcat_Creek_Production_2018.jpg",
     width=3.2,
     height=3.2,
     units="in",
     res=300)
plot.new()
# bottom, left, top, right
par(mar=c(2, 4, 2, 2))
barplot(WCS18prod$production,
        col = c("#404788FF", "#FDE725FF"),
        main = "Wildcat Creek Production 2018",
        axes = FALSE,
        names.arg=(c("Production", "Availability")),
        ylab = expression(paste("lbs ", "acre"^"-1", " ± SE")),
        cex.lab = 1,
        cex.main = 1,
        ylim = c(0, 6500))
axis(2,at=c(seq(0,6500,1000)),labels=c(seq(0,6500,1000)), cex.axis= 0.5, las = 2)
segments(0.7, mystats[7, 4] - mystats[7, 6], 0.7,
         mystats[7, 4] + mystats[7, 6], lwd = 1)
arrows(0.7, mystats[7, 4] - mystats[7, 6], 0.7,
       mystats[7, 4] + mystats[7, 6], lwd = 1, angle = 90,
       code = 3, length = 0.05)
segments(1.9, mystats[8, 4] - mystats[8, 6], 1.9,
         mystats[8, 4] + mystats[8, 6], lwd = 1)
arrows(1.9, mystats[8, 4] - mystats[8, 6], 1.9,
       mystats[8, 4] + mystats[8, 6], lwd = 1, angle = 90,
       code = 3, length = 0.05)
text(0.7, 3900, "3271", pos = 3, cex = 0.75)
text(1.9, 300, "192", pos = 3, cex = 0.75)
dev.off()
```

```{r}
## calculate % utilization
# this is a bad way to calculate utilization
# subsetting dataframes by index is prone to error
BGW17Utilization <- (mystats[1, 4]-mystats[2, 4])/mystats[1, 4]
WCS17Utilization <- (mystats[3, 4]-mystats[4, 4])/mystats[3, 4]
BGW18Utilization <- (mystats[5, 4]-mystats[6, 4])/mystats[5, 4]
WCS18Utilization <- (mystats[7, 4]-mystats[8, 4])/mystats[7, 4]

## t test for production values between years
t.test(BGW17E$TotalDry, BGW18E$TotalDry)
t.test(WCS17E$TotalDry, WCS18E$TotalDry)

## t test for utilization values between years
t.test(BGW17G$TotalDry, BGW18G$TotalDry)
t.test(WCS17G$TotalDry, WCS18G$TotalDry)
```
